# run cargo init
cargoinit:
	cargo init

# create cargo run
cargorun:
	cargo run --bin 01_hello_world
# cargo run --bin mylib

# create cargo build
cargobuild:
	cargo build

# create cargo build --release
cargobuildrelease:
	cargo build --release
# cargo build --package mylib

# create cargo clean
cargoclean:
	cargo clean

# create cargo doc
cargodoc:
	cargo doc

# create cargo test
cargotest:
	cargo test

# create cargo update
cargoupdate:
	cargo update
