apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kaniko-task
spec:
  inputs:
    resources:
      - name: source
        type: git
      - name: dockerfile
        type: git
  outputs:
    resources:
      - name: builtImage
        type: image
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:latest
      command:
        - /kaniko/executor
      args:
        - --context=/workspace/source
        - --dockerfile=/workspace/dockerfile/Dockerfile
        - --destination={{outputs.resources.builtImage.url}}
      env:
        - name: DOCKER_CONFIG
          value: /tekton/home/.docker
        - name: DOCKER_CONFIG_JSON
          value: /tekton/home/.docker/config.json
      volumeMounts:
        - name: kaniko-config
          mountPath: /tekton/home/.docker
        - name: docker-socket
          mountPath: /var/run/docker.sock
  volumes:
    - name: kaniko-config
      configMap:
        name: kaniko-config
    - name: docker-socket
      hostPath:
        path: /var/run/docker.sock
