repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
# -   repo: https://github.com/pycqa/pylint
#     rev: v3.0.0a6
#     hooks:
#     -   id: pylint
#     args:
#     -   --errors-only
#     # ignore rule E0401
#     -   --disable=E0401
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort

# -   repo: https://github.com/gruntwork-io/pre-commit
#     rev: v0.1.20 # Get the latest from: https://github.com/gruntwork-io/pre-commit/releases
#     hooks:
#       - id: terraform-fmt
#       - id: tflint
#       - id: shellcheck
#       - id: gofmt
#       - id: golint
-   repo: https://github.com/pycqa/pylint
    rev: v3.0.0a6
    hooks:
    -   id: pylint
        args:
        - --errors-only
        # ignore rule E0401
        - --disable=E0401
        # - --disable=missing-docstring
