# argo workflow with three stages with retry
---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
spec:
  entrypoint: whalesay
  templates:
  - name: whalesay
    retryStrategy:
      limit: 3
      backoff:
        duration: "10"
        factor: 2
        maxDuration: "1m"
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["hello world"]
  - name: whalesay2
    retryStrategy:
      limit: 3
      backoff:
        duration: "10"
        factor: 2
        maxDuration: "1m"
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["hello world2"]
  - name: whalesay3
    retryStrategy:
      limit: 3
      backoff:
        duration: "10"
        factor: 2
        maxDuration: "1m"
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["hello world3"]
