apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-cleaner-cron-job-rolebinding
subjects:
- kind: ServiceAccount
  name: argo-cleaner-cron-job
  namespace: argo
roleRef:
  kind: Role
  name: argo-cleaner-cron-job-role
  apiGroup: rbac.authorization.k8s.io
