[package]
name = "rust_cuda_sample"
version = "0.1.0"
edition = "2018"

[dependencies]
rustacuda = "0.5"
rustacuda-core = "0.1"
rustacuda-derive = "0.1"
rand = "0.8"

[features]
default = ["cuda"]
cuda = ["rustacuda/cuda"]
