name: Smoke Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Start Flask server
      run: |
        python app.py &

    - name: Wait for server to start
      run: sleep 5s

    - name: Run smoke tests
      run: |
        python tests/smoke_test.py

    - name: Stop Flask server
      run: |
        kill $(lsof -t -i:5000)
