[package]
name = "swagger"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
swagger-ui = "0.1.5"
tokio = "1.31.0"
warp = "0.3.5"
swagger = "6.3.0"
