# This example demonstrates the use of retry back offs
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: retry-backoff-
spec:
  entrypoint: retry-backoff
  templates:
  - name: retry-backoff
    retryStrategy:
      limit: 2 # the number of times to retry the container before considering the step failed
      retryPolicy: Always
      backoff:
        duration: 3m # 3 minutes back off loop
        factor: 2 # the factor to multiply the duration by each iteration(2^1min, 2^2min, 2^3min)
        maxDuration: 60m # the maximum amount of time allowed for the backoff loop (2*1,2*2,2*3..2*30min)
      affinity:
        nodeAntiAffinity: {}
    container:
      image: python:alpine3.6
      command: ["python", -c]
      # fail with a (1/15*100)% probability
      args: ["import random; import time; import sys; time.sleep(120);exit_code =random.choice([0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]);sys.exit(exit_code)"]
